### ISSUE TITLE
Check reports for dependencies on specific parameters e.g. detector voltage

### ISSUE THREAD

**Issue by carolinesands** [phenomecentre/nPYc-Toolbox#57]
And fix where necessary

**Comment by Gscorreia89** [comment]
Some of the changes in the mzML import branch fixed this: https://github.com/phenomecentre/nPYc-Toolbox/pull/67 
The 'feature summary' and 'correlation to dilution' reports now skip the plot if detector information is not available. 

However, would be good to do a more general code review, and maybe make the plotting functions more flexible - instead of plotting 'detector' or other hardcoded parameters, they could plot any passed parameter. The choice of parameter would then be controlled at report level.

**Comment by Gscorreia89** [comment]
Closing this for now, but will be opening an enhancement issue for future work in making the plotting functions more flexible.
